spring:
  application:
    name: cmb-fiance

  ai:
    mcp:
      server:
        name: cmb-fiance-mcp-server
        version: 1.0.0
        type: SYNC

  datasource:
    url: jdbc:mysql://localhost:3306/cmb_finance
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

data-sync-task:
  zs-tags: [ ]
  risk-types: [ ]
  hot-product-list-data-sync-enabled: false
  subscribed-products:
    - sales-platform: cmb
      product-type: fund
      product-sale-code: "003958"

    - sales-platform: cmb
      product-type: fund
      product-sale-code: "161130"

    - sales-platform: cmb
      product-type: fund
      product-sale-code: "004253"

    - sales-platform: cmb
      product-type: fund
      product-sale-code: "050025"
